name: Workflow 2

on:
  repository_dispatch:

jobs:
  respond-to-trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Event Payload
        run: |
          echo "Branch: ${{ github.event.client_payload.branch }}"
          echo "Commit: ${{ github.event.client_payload.commit }}"
          echo "Build Number: ${{ github.event.client_payload.build_number }}"

      - name: Perform Workflow 2 Tasks
        run: echo "Workflow 2 executed successfully!"
  
      - name: Send Teams Notification
        if: always()
        shell: pwsh
        run: |
          Write-Host "Sending notification to Microsoft Teams"

          $status = '${{ job.status }}'
          $suite = "Sanity"
          $environment = "Staging"
          $site = "Latest"
          $buildNumber = '1.0.0108'
      
          if ($status -eq 'failure') {
            $result = "FAILED"
            $themeColor = "FF0000"
          } else {
            $result = "PASSED"
            $themeColor = "00FF00"
          }
      
          $body = @{
            "@type" = "MessageCard"
            "@context" = "http://schema.org/extensions"
            "text" = "**Execution of automated test completed with the following details:**"
            "title" = "Automation Test Notification"
            "themeColor" = $themeColor
            "sections" = @(
              @{
                "facts" = @(
                  @{ "name" = "   Suite"; "value" = $suite }
                  @{ "name" = "   Result"; "value" = $result }
                  @{ "name" = "   Build No."; "value" = $buildNumber },
                  @{ "name" = "   Environment"; "value" = $environment },
                  @{ "name" = "   Site"; "value" = $site }
                )
              }
            )
          } | ConvertTo-Json -Depth 10 -Compress
      
          $webhookUrl = 'https://tylertech.webhook.office.com/webhookb2/fee32edf-9a7d-413c-aaaf-009cd84a3fc4@7cc5f0f9-ee5b-4106-a62d-1b9f7be46118/IncomingWebhook/5eaf925a5ac2406e9380cb53e926de50/00a91875-899e-4b0d-b991-89b502288683/V2ndRYsqIbN4dTiiVgMs8RdG-I86snZPbBzv4JC2OZsR81'
          $response = Invoke-RestMethod -Uri $webhookUrl -Method Post -Body $body -ContentType 'application/json'
          if (-not $response) {
            Write-Host "Failed to send Teams notification"
            exit 1
          }
      
          Write-Host "Notification sent successfully"
